"""
Pydantic models — HSK Vocabulary word schema.
"""

from pydantic import BaseModel, Field
from typing import Literal


class HSKWord(BaseModel):
    """
    Master vocabulary entry stored in the 'vocabulary' collection.
    Seeded once from the HSK 2.0 wordlist (~1,200 entries).
    """

    hanzi: str = Field(..., description="The Chinese character(s), e.g. '电'")
    pinyin: str = Field(..., description="Romanized pronunciation, e.g. 'diàn'")
    meaning: str = Field(..., description="Primary English meaning")
    hsk_level: int = Field(..., ge=1, le=4, description="HSK level 1–4")
    part_of_speech: str = Field(default="", description="e.g. 'noun', 'verb', 'adjective'")
    tags: list[str] = Field(default_factory=list, description="Topic tags")
    radical: str | None = Field(default=None, description="Primary radical")
    stroke_count: int | None = Field(default=None, description="Total stroke count")
    traditional: str | None = Field(default=None, description="Traditional form if different")


class HSKWordResponse(HSKWord):
    """HSK word enriched with its current SRS state for API responses."""

    word_state: "WordStateResponse | None" = None


class ExampleSentence(BaseModel):
    zh: str
    pinyin: str
    en: str


class LessonPayload(BaseModel):
    """Structured lesson generated by the LLM (OpenRouter → Claude Sonnet)."""

    hanzi: str
    pinyin: str
    tone_description: str
    radical: str
    meaning_core: str
    etymology: str
    example_sentences: list[ExampleSentence]
    cultural_note: str
    memory_hook: str
    common_compounds: list[ExampleSentence] = Field(default_factory=list)


# avoid circular import for forward ref
from api.models.user_state import WordStateResponse  # noqa: E402
HSKWordResponse.model_rebuild()
